apiVersion: torpedo.k8s.att.io/v1
kind: Torpedo
metadata:
  name: test-resilience
spec:
  orchestrator_plugin: "torpedo-traffic-orchestrator"
  chaos_plugin: "torpedo-chaos"
  # Varies from plugin image to image
  job-params:
    - - name: test-resilience
# Common params
# Execution Time in seconds
        job-duration: 120
# Number of requests to perform for both chaos and traffic.
# Comes into play when job-duration is 0. job-duration takes precedence
        count: 0
        volume-storage-class: 'standard'
        volume-storage: '1Gi'
        volume-name: 'my-vol'
# Uncomment if accessing remote cluster and provide cluster details
# under chaos-params
        # remote-cluster: 'True'
# Chaos Params
        chaos-params:
# uncomment and provide details if remote-cluster set to true
          # cluster-config:
          #   name: ''
          #   apiserver: ''
          #   token: ''
# Needed incase we want to use some other chaos tool
          image: ''
# Args to pass to the chaos image
          extra-args: ''
# Interval in seconds between 2 kills
          kill-interval: 30
# number of pods to be killed simultaneously
          kill-count: 30
          same-node: False
# Label of pods you want to kill
          pod-labels:
            - 'app=db'
# Nodes you want to target. Can be combined with pod labels to target pod on
# specific nodes
          node-labels: []
# Required in case of node drain scenarios
          nodes: ''
          max-nodes: 1

# Namespace you want to target
          namespace: test-ns
# Traffic Params. You can comment below section if you want to opt out
        traffic-params:
          #service-mapping: promenade
          traffic-module: generic
# If custom image and args passed then other params will not be considered
          custom:
            image: ''
            args: ''
          endpoint: ''
          request: 'get/post'
          extra-headers: ''
          body: ''
          extra-args: ''
          auth:
            auth-url: http://keystone.test-ns.svc.cluster.local:5000/v3
            username: admin
            password: abcdefghijk


# Sanity Params
        sanity-params:
          image: ''
          extra-args: ''
